version: '3.8'
services:
  tipo-mysql-server:
    build:
      context: .
      target: BUILD_SERVER
      network: mysql-tipo_default
    image: karta0989006/tipo-mysql-server
    ports:
      - 5000:5000
    networks:
      - mysql-tipo_default
    # command: ["npm", "run", "dev"] 
    command: ["npm", "start"]


networks:
  mysql-tipo_default:
    external:
      name: mysql-tipo_default
